# Generated by Django 4.1.1 on 2022-10-25 21:59

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('telefono_contacto', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Comprador',
                'verbose_name_plural': 'Compradores',
            },
        ),
        migrations.CreateModel(
            name='comuna',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=50)),
                ('provincia_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Corredor',
                'verbose_name_plural': 'Corredores',
            },
        ),
        migrations.CreateModel(
            name='Documentos_Legales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to=core.models.user_directory_path)),
                ('titulo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado de Ocupacion',
                'verbose_name_plural': 'Estados de Ocupacion',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.user_directory_path)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('keywords', models.TextField(default='0')),
                ('correo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Metadata',
                'verbose_name_plural': 'Metadatas',
            },
        ),
        migrations.CreateModel(
            name='metodo_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Metodo de Pago',
                'verbose_name_plural': 'Metodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='provincias',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=50)),
                ('region_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='regiones',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='tipo_operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Operacion',
                'verbose_name_plural': 'Tipos de Operaciones',
            },
        ),
        migrations.CreateModel(
            name='tipo_propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Propiedad',
                'verbose_name_plural': 'Tipos de Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('telefono_contacto', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('estado_uso', models.TextField(default='Buen estado. Solo necesita pintura y reparaciones menores.')),
                ('comision_venta', models.TextField(default='2% + IVA del valor de venta (con Factura Excenta)', max_length=200)),
                ('rol', models.CharField(max_length=50)),
                ('precio', models.IntegerField(default=0)),
                ('superficie_construida', models.FloatField(default=0)),
                ('superficie_terraza', models.FloatField(default=0)),
                ('superficie_terreno', models.FloatField(default=0)),
                ('dormitorios', models.IntegerField(default=0)),
                ('baños', models.IntegerField(default=0)),
                ('estacionamientos', models.IntegerField(default=0)),
                ('bodegas', models.IntegerField(default=0)),
                ('gastos_comunes', models.IntegerField(default=0)),
                ('arriendo_maximo', models.IntegerField(default=0)),
                ('arriendo_minimo', models.IntegerField(default=0)),
                ('arriendo_actual', models.IntegerField(default=0)),
                ('garantia_necesaria', models.IntegerField(default=0)),
                ('destacado', models.BooleanField(default=False)),
                ('bestoff', models.BooleanField(default=False)),
                ('aceptan_contado', models.BooleanField(default=True)),
                ('aceptan_credito', models.BooleanField(default=False)),
                ('aceptan_subsidio', models.BooleanField(default=False)),
                ('acetan_permuta', models.BooleanField(default=False)),
                ('aceptan_ofertas', models.BooleanField(default=False)),
                ('propiedad_bancaria', models.BooleanField(default=False)),
                ('video', models.FileField(blank=True, null=True, upload_to=core.models.user_directory_path)),
                ('youtube_video', models.CharField(blank=True, max_length=200, null=True, verbose_name='Youtube Video (Opcional)')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('contribuciones', models.IntegerField(default=0)),
                ('tasacion_fiscal', models.IntegerField(default=0)),
                ('tasacion_comercial', models.IntegerField(default=0)),
                ('fecha_venta_anterior', models.DateField(blank=True, null=True)),
                ('precio_venta_anterior', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.TextField(blank=True, max_length=200, null=True, unique=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
                ('corredor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.corredor')),
                ('documentos_legales', models.ManyToManyField(blank=True, to='core.documentos_legales')),
                ('estado_ocupacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.estado_ocupacion')),
                ('imagenes', models.ManyToManyField(blank=True, to='core.image')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.moneda')),
                ('tipo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo_operacion')),
                ('tipo_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo_propiedad')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendedor')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.moneda')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.propiedad')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='id_propiedades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.propiedad'),
        ),
        migrations.AddField(
            model_name='documentos_legales',
            name='id_propiedades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.propiedad'),
        ),
    ]
