# Generated by Django 4.1.1 on 2022-10-26 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.moneda')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.propiedad')),
            ],
        ),
    ]
