# Generated by Django 4.1.1 on 2022-11-29 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ofertas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='moneda_arriendo_actual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ofertas',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comprador'),
        ),
        migrations.DeleteModel(
            name='oferta',
        ),
        migrations.AddField(
            model_name='ofertas',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.estado_oferta'),
            preserve_default=False,
        ),
    ]
