# Generated by Django 4.1.1 on 2022-11-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estado_oferta_moneda_arriendo_actual_ofertas_fecha_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ofertas',
            new_name='Oferta',
        ),
        migrations.AlterModelOptions(
            name='oferta',
            options={'verbose_name': 'Oferta', 'verbose_name_plural': 'Ofertas'},
        ),
    ]
