# Generated by Django 4.1.1 on 2022-12-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactos'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='forma_pago',
            field=models.CharField(default='Con Crédito Hipotecario', max_length=200),
            preserve_default=False,
        ),
    ]
