# Generated by Django 4.1.1 on 2022-12-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_oferta_forma_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactos',
            options={'verbose_name': 'Contactos', 'verbose_name_plural': 'Contactos'},
        ),
    ]
