# Generated by Django 4.1.1 on 2022-12-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_contactos_options_remove_oferta_forma_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentos_legales',
            options={'verbose_name': 'Documento Legal', 'verbose_name_plural': 'Documentos Legales'},
        ),
    ]
