# Generated by Django 4.1.1 on 2022-12-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_documentos_legales_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='forma_pago',
            field=models.CharField(default='Crédito Hipotecario', max_length=150),
        ),
    ]
