# Generated by Django 4.1.1 on 2022-12-13 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_oferta_forma_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.estado_oferta'),
        ),
    ]
