# Generated by Django 4.1.1 on 2022-12-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_oferta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='aceptada',
            field=models.BooleanField(default=False),
        ),
    ]
