# Generated by Django 4.1.1 on 2023-08-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_usersmetadata_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmetadata',
            name='garantia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersmetadata',
            name='rut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
