# Generated by Django 4.1.1 on 2023-08-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_usersmetadata_garantia_usersmetadata_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
